In [22]:
#  Import ML tools
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.preprocessing import StandardScaler

In [2]:
# Import packages
import pandas as pd
import numpy as np

In [26]:
# Train-test split
df = pd.read_csv('final_pune___data.csv')

In [27]:
# Initialize the StandardScaler
scaler = StandardScaler()

# Fit and transform the 'total_sqft' column
df['scaled_sqft'] = scaler.fit_transform(df[['total_sqft']])

In [28]:
df.drop(['total_sqft'], axis=1, inplace=True)

In [29]:
df.head()

,area_type_0,area_type_1,area_type_2,bath,balcony,price,site_location_0,site_location_1,site_location_2,site_location_3,site_location_4,site_location_5,site_location_6,BHK,scaled_sqft
0,0,0,1,2.0,1.0,39.07,0,0,0,0,0,0,1,2,-0.392251
1,0,1,0,5.0,3.0,120.00,0,0,0,0,0,1,0,4,0.936037
2,0,1,1,2.0,3.0,62.00,0,0,0,0,0,1,1,3,-0.061900
3,0,0,1,3.0,1.0,95.00,0,0,0,0,1,0,0,3,0.007783
4,0,0,1,2.0,1.0,51.00,0,0,0,0,1,0,1,2,-0.268370

In [30]:
X = df.drop('price', axis=1)
y = df['price']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [24]:
df.head(20)

,area_type_0,area_type_1,area_type_2,total_sqft,bath,balcony,price,site_location_0,site_location_1,site_location_2,site_location_3,site_location_4,site_location_5,site_location_6,BHK,scaled_sqft
0,0,0,1,1056.0,2.0,1.0,39.07,0,0,0,0,0,0,1,2,-0.392251
1,0,1,0,2600.0,5.0,3.0,120.00,0,0,0,0,0,1,0,4,0.936037
2,0,1,1,1440.0,2.0,3.0,62.00,0,0,0,0,0,1,1,3,-0.061900
3,0,0,1,1521.0,3.0,1.0,95.00,0,0,0,0,1,0,0,3,0.007783
4,0,0,1,1200.0,2.0,1.0,51.00,0,0,0,0,1,0,1,2,-0.268370
5,0,0,1,1170.0,2.0,1.0,38.00,0,0,0,0,1,1,0,2,-0.294178
6,0,0,1,1310.0,3.0,1.0,63.25,0,0,0,0,1,1,1,3,-0.173738
7,0,0,1,1800.0,2.0,2.0,70.00,0,0,0,1,0,0,0,3,0.247804
8,0,1,0,2785.0,5.0,3.0,295.00,0,0,0,1,0,0,1,4,1.095190
9,0,0,1,1000.0,2.0,1.0,38.00,0,0,0,1,0,1,0,2,-0.440428
10,0,1,1,1100.0,2.0,2.0,40.00,0,0,0,1,0,1,1,2,-0.354399
11,0,1,0,2250.0,3.0,2.0,148.00,0,0,0,1,1,0,0,3,0.634935
12,0,0,1,1175.0,2.0,2.0,73.50,0,0,0,1,1,0,1,2,-0.289877
13,0,0,1,1180.0,3.0,2.0,48.00,0,0,0,1,1,1,0,3,-0.285575
14,0,0,1,1540.0,3.0,3.0,60.00,0,0,0,1,1,1,1,3,0.024129
15,0,0,1,2770.0,4.0,2.0,290.00,0,0,1,0,0,0,0,3,1.082286
16,0,0,1,1100.0,2.0,2.0,48.00,0,0,1,0,0,0,1,2,-0.354399
17,0,1,1,600.0,1.0,1.0,15.00,0,0,1,0,0,1,0,1,-0.784544
18,0,0,1,1755.0,3.0,1.0,122.00,0,0,1,0,0,1,1,3,0.209091
19,0,1,0,2800.0,5.0,2.0,380.00,0,0,1,0,1,0,0,4,1.108095

In [31]:
# Train Linear Regression
lr = LinearRegression()
lr.fit(X_train, y_train)
pred = lr.predict(X_test)

In [32]:
#  Evaluate
print("R2 Score:", r2_score(y_test, pred))
print("MAE:", mean_absolute_error(y_test, pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, pred)))

R2 Score: 0.19246932352687973
MAE: 38.585503141094094
RMSE: 117.8429348901339

In [33]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(random_state=42)
rf.fit(X_train, y_train)
rf_pred = rf.predict(X_test)

In [34]:
#  Evaluate RF
print("R2 Score:", r2_score(y_test, rf_pred))
print("MAE:", mean_absolute_error(y_test, rf_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, rf_pred)))

R2 Score: 0.6841530689355315
MAE: 33.43742371899998
RMSE: 73.69913085320316

In [35]:
from xgboost import XGBRegressor

xgb = XGBRegressor(random_state=42)
xgb.fit(X_train, y_train)
xgb_pred = xgb.predict(X_test)

In [36]:
# Evaluate XGBoost
print("R2 Score:", r2_score(y_test, xgb_pred))
print("MAE:", mean_absolute_error(y_test, xgb_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, xgb_pred)))

R2 Score: 0.614631637481786
MAE: 34.07100029868537
RMSE: 81.4070588223478

In [14]:
!pip install catboost

Collecting catboost
  Downloading catboost-1.2.8-cp311-cp311-manylinux2014_x86_64.whl.metadata (1.2 kB)
Requirement already satisfied: graphviz in /usr/local/lib/python3.11/dist-packages (from catboost) (0.20.3)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.11/dist-packages (from catboost) (3.10.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /usr/local/lib/python3.11/dist-packages (from catboost) (2.0.2)
Requirement already satisfied: pandas>=0.24 in /usr/local/lib/python3.11/dist-packages (from catboost) (2.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.11/dist-packages (from catboost) (1.14.1)
Requirement already satisfied: plotly in /usr/local/lib/python3.11/dist-packages (from catboost) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.11/dist-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.24->catboost) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.24->catboost) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->catboost) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib->catboost) (4.57.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->catboost) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib->catboost) (24.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.11/dist-packages (from matplotlib->catboost) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->catboost) (3.2.3)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.11/dist-packages (from plotly->catboost) (9.1.2)
Downloading catboost-1.2.8-cp311-cp311-manylinux2014_x86_64.whl (99.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.2/99.2 MB 5.2 MB/s eta 0:00:00
Installing collected packages: catboost
Successfully installed catboost-1.2.8

In [15]:
from catboost import CatBoostRegressor

In [16]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10125 entries, 5437 to 7270
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   area_type_0      10125 non-null  int64
 1   area_type_1      10125 non-null  int64
 2   area_type_2      10125 non-null  int64
 3   total_sqft       10125 non-null  float64
 4   bath             10125 non-null  float64
 5   balcony          10125 non-null  float64
 6   site_location_0  10125 non-null  int64
 7   site_location_1  10125 non-null  int64
 8   site_location_2  10125 non-null  int64
 9   site_location_3  10125 non-null  int64
 10  site_location_4  10125 non-null  int64
 11  site_location_5  10125 non-null  int64
 12  site_location_6  10125 non-null  int64
 13  BHK              10125 non-null  int64
dtypes: float64(3), int64(11)
memory usage: 1.2 MB

In [37]:
# Optional: Fill missing values
X_train.fillna(0, inplace=True)
X_test.fillna(0, inplace=True)

# Optional: Make sure all are numeric
X_train = X_train.apply(pd.to_numeric, errors='coerce')
X_test = X_test.apply(pd.to_numeric, errors='coerce')

In [38]:
cat = CatBoostRegressor(verbose=0, random_state=42)
cat.fit(X_train, y_train)
cat_pred = cat.predict(X_test)

In [39]:
#  Evaluate CatBoost
print("R2 Score:", r2_score(y_test, cat_pred))
print("MAE:", mean_absolute_error(y_test, cat_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, cat_pred)))

R2 Score: 0.6669857118289029
MAE: 32.06409151544747
RMSE: 75.6755296504007